version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
    ports:
      - 13306:3306
#  db:
#    image: postgres:11.5-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: password
#    ports:
#      - 5432:5432
